import httpx
import json
import logging
from typing import List, Dict, Any, Optional
from visionspace.backend.config.config import settings
from visionspace.backend.database.models import Recommendation as DBRecommendation
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

MASTER_PROMPT = """You are VisionSpace AI Product Retrieval Agent.

Your task is to analyze product search results collected from multiple sources including:
* Serper API
* Tavily API
* SerpAPI
* Playwright scraping
* Local Database

Your objectives are:
1. Understand the user's intent.
2. Analyze products based on:
* Price
* Rating
* Reviews
* Dimensions
* Brand
* Availability
* Store reputation
* Suitability to user requirements

3. Recommend the best products.
4. Explain WHY each product is recommended.

5. If dimensions are available:
* Check whether the product fits the user's room dimensions.
* Mention walking clearance.
* Mention space utilization.

6. Rank products using:
Priority:
1. User constraints
2. Suitability
3. Rating
4. Reviews
5. Price
6. Brand reputation

7. If product information is missing:
* State that information is unavailable.
* Never hallucinate values.

8. Output MUST be JSON:
{
  "recommended_products": [
    {
      "title": "",
      "price": "",
      "rating": "",
      "store": "",
      "url": "",
      "reason": ""
    }
  ],
  "best_choice": {
    "title": "",
    "reason": ""
  },
  "summary": ""
}
"""

def generate_heuristic_recommendation(query: str, products: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Deterministic programmatic recommendation generator used if LM Studio is offline or errors.
    """
    recommended = []
    for p in products[:3]:
        p_curr = (p.get('currency') or 'INR').upper().strip()
        curr_symbol = "₹" if p_curr == "INR" else "$" if p_curr == "USD" else "€" if p_curr == "EUR" else "£" if p_curr == "GBP" else f"{p_curr} "
        price_str = f"{curr_symbol}{p['price']}" if p.get('price') else "N/A"
        rating_str = f"{p['rating']}/5" if p.get('rating') else "N/A"
        recommended.append({
            "title": p.get("title", "Unknown Product"),
            "price": price_str,
            "rating": rating_str,
            "store": p.get("store") or "N/A",
            "url": p.get("url") or "",
            "image": p.get("image"),
            "reason": (
                "Ranked high based on rating, availability, and cost constraints. "
                "(Generated by local fallback heuristics, the selected LLM was offline/unreachable)"
            )
        })
        
    best_item = recommended[0] if recommended else {"title": "No products available", "reason": "No products met constraints."}
    
    return {
        "recommended_products": recommended,
        "best_choice": {
            "title": best_item["title"],
            "reason": best_item.get("reason", "No suitable products were retrieved."),
            "image": best_item.get("image")
        },
        "summary": "This is a programmatic heuristic recommendation report. The selected LLM provider was offline, returned an error, or was unreachable."
    }

async def get_llm_recommendation(
    query: str,
    products: List[Dict[str, Any]],
    room_dimensions: Optional[str] = None,
    db: Optional[Session] = None,
    provider: Optional[str] = None,
    model: Optional[str] = None,
    openrouter_key: Optional[str] = None,
    gemini_key: Optional[str] = None,
    grok_key: Optional[str] = None,
    groq_key: Optional[str] = None
) -> Dict[str, Any]:
    """
    Sends the parsed products and query to the selected LLM provider (LM Studio, OpenRouter, Gemini, Grok, or Groq)
    for recommendation report generation. Logs the result to the SQL database.
    """
    if not products:
        return {
            "recommended_products": [],
            "best_choice": {"title": "None", "reason": "No candidate products available to rank."},
            "summary": "No product listings were retrieved for this query."
        }
        
    # Limit to top 5 ranked candidates to keep token usage low and generation fast on local models
    products = products[:5]
        
    # Format candidate products text context
    user_content = f"User Query: {query}\n"
    if room_dimensions:
        user_content += f"Room Dimensions constraints: {room_dimensions}\n"
        
    user_content += "\nCandidate products list:\n"
    for i, p in enumerate(products):
        # Format candidate product price using its native currency
        curr_symbol = p.get('currency') or 'INR'
        price_str = f"{curr_symbol} {p.get('price')}" if p.get('price') else "N/A"
        user_content += (
            f"Product #{i+1}:\n"
            f"  Title: {p.get('title')}\n"
            f"  Brand: {p.get('brand')}\n"
            f"  Price: {price_str}\n"
            f"  Rating: {p.get('rating')}\n"
            f"  Reviews: {p.get('reviews')}\n"
            f"  Dimensions: {p.get('dimensions')}\n"
            f"  Availability: {p.get('availability')}\n"
            f"  Store: {p.get('store')}\n"
            f"  URL: {p.get('url')}\n\n"
        )
        
    # Resolve provider and model (fallback to settings if not provided)
    prov = (provider or settings.LLM_PROVIDER or "lm-studio").lower().strip()
    
    api_url = ""
    api_key = ""
    model_name = model or settings.LLM_MODEL or ""
    headers = {"Content-Type": "application/json"}
    
    if prov == "openrouter":
        api_url = "https://openrouter.ai/api/v1/chat/completions"
        api_key = openrouter_key or settings.OPENROUTER_API_KEY
        if not api_key:
            logger.warning("OpenRouter API key is missing. Falling back to local LM Studio...")
            prov = "lm-studio"
        else:
            model_name = model_name or "google/gemma-4-31b-it:free"
            headers["Authorization"] = f"Bearer {api_key}"
            headers["HTTP-Referer"] = "https://github.com/VisionAI-PRO/product-retrieval-agent"
            headers["X-Title"] = "VisionSpace Product Retrieval Agent"
            
    if prov == "gemini":
        api_key = gemini_key or settings.GEMINI_API_KEY
        if not api_key:
            logger.warning("Gemini API key is missing. Falling back to local LM Studio...")
            prov = "lm-studio"
        else:
            model_name = model_name or "gemini-2.5-flash"
            if not model_name.startswith("models/"):
                api_model = f"models/{model_name}"
            else:
                api_model = model_name
            api_url = f"https://generativelanguage.googleapis.com/v1beta/{api_model}:generateContent"
            headers = {
                "Content-Type": "application/json",
                "X-goog-api-key": api_key
            }
            
    if prov == "grok":
        api_url = "https://api.x.ai/v1/chat/completions"
        api_key = grok_key or settings.GROK_API_KEY
        if not api_key:
            logger.warning("Grok API key is missing. Falling back to local LM Studio...")
            prov = "lm-studio"
        else:
            model_name = model_name or "grok-2-1212"
            headers["Authorization"] = f"Bearer {api_key}"

    if prov == "groq":
        api_url = "https://api.groq.com/openai/v1/chat/completions"
        api_key = groq_key or settings.GROQ_API_KEY
        if not api_key:
            logger.warning("Groq API key is missing. Falling back to local LM Studio...")
            prov = "lm-studio"
        else:
            model_name = model_name or "llama-3.3-70b-versatile"
            headers["Authorization"] = f"Bearer {api_key}"
            
    # If it is lm-studio, or fell back to it
    if prov == "lm-studio":
        api_url = f"{settings.LM_STUDIO_BASE_URL.rstrip('/')}/chat/completions"
        api_key = settings.LM_STUDIO_API_KEY or "lm-studio"
        headers["Authorization"] = f"Bearer {api_key}"
        
        # Auto-detect loaded model name if not specified
        if not model_name:
            models_url = f"{settings.LM_STUDIO_BASE_URL.rstrip('/')}/models"
            try:
                logger.info(f"Checking active models on LM Studio at {models_url}")
                with httpx.Client() as client:
                    models_res = client.get(models_url, timeout=5.0)
                    if models_res.status_code == 200:
                        models_data = models_res.json()
                        if "data" in models_data and models_data["data"]:
                            model_name = models_data["data"][0]["id"]
                            logger.info(f"Auto-detected active LM Studio model: '{model_name}'")
            except Exception as me:
                logger.warning(f"Could not auto-detect active model, using default 'qwen/qwen3-1.7b'. Error: {me}")
                model_name = "qwen/qwen3-1.7b"
                
    logger.info(f"Using LLM Provider: {prov} | Model: {model_name}")

    # Build payload based on provider
    if prov == "gemini":
        combined_content = f"{MASTER_PROMPT}\n\nUser request & candidate products:\n{user_content}"
        payload = {
            "contents": [
                {
                    "role": "user",
                    "parts": [
                        {"text": combined_content}
                    ]
                }
            ],
            "generationConfig": {
                "responseMimeType": "application/json",
                "temperature": 0.1
            }
        }
    else:
        payload = {
            "model": model_name,
            "messages": [
                {"role": "system", "content": MASTER_PROMPT},
                {"role": "user", "content": user_content}
            ],
            "temperature": 0.1,
            "response_format": {"type": "json_object"}
        }
    
    try:
        logger.info(f"Invoking {prov} model at: {api_url}")
        async with httpx.AsyncClient() as client:
            response = await client.post(api_url, json=payload, headers=headers, timeout=180.0)
            
            # Auto-fallback retry if model does not support response_format (standard for smaller models returning 400)
            if prov != "gemini" and response.status_code == 400 and "response_format" in payload:
                logger.warning("LLM provider returned 400 Bad Request. Retrying without json_object response format constraint...")
                retry_payload = payload.copy()
                retry_payload.pop("response_format", None)
                response = await client.post(api_url, json=retry_payload, headers=headers, timeout=180.0)
            
        if response.status_code == 200:
            result = response.json()
            if prov == "gemini":
                parts = result["candidates"][0]["content"]["parts"]
                non_thought_parts = [p.get("text", "") for p in parts if not p.get("thought")]
                if non_thought_parts:
                    llm_text = "".join(non_thought_parts)
                else:
                    llm_text = "".join([p.get("text", "") for p in parts])
            else:
                llm_text = result["choices"][0]["message"]["content"]
            
            # Clean up LLM response markup if model returned it inside a markdown block
            llm_text_clean = llm_text.strip()
            if llm_text_clean.startswith("```json"):
                llm_text_clean = llm_text_clean.split("```json", 1)[1].rsplit("```", 1)[0].strip()
            elif llm_text_clean.startswith("```"):
                llm_text_clean = llm_text_clean.split("```", 1)[1].rsplit("```", 1)[0].strip()
                
            parsed_recommendation = json.loads(llm_text_clean)
            
            # Match titles to find image URLs from candidate products list
            def get_matching_image(title_str: str) -> Optional[str]:
                if not title_str:
                    return None
                title_lower = title_str.lower()
                for p in products:
                    p_title = p.get("title", "").lower()
                    if p_title == title_lower or p_title in title_lower or title_lower in p_title:
                        return p.get("image")
                return None

            if isinstance(parsed_recommendation, dict):
                # Match image for best choice
                best_choice_dict = parsed_recommendation.get("best_choice")
                if isinstance(best_choice_dict, dict):
                    best_choice_dict["image"] = get_matching_image(best_choice_dict.get("title"))

                # Match image for recommended products list
                recs = parsed_recommendation.get("recommended_products")
                if isinstance(recs, list):
                    for rec in recs:
                        if isinstance(rec, dict):
                            rec["image"] = get_matching_image(rec.get("title"))
            
            # Persist to database if db session is available
            if db:
                try:
                    best_title = parsed_recommendation.get("best_choice", {}).get("title", "")
                    best_reason = parsed_recommendation.get("best_choice", {}).get("reason", "")
                    db_rec = DBRecommendation(
                        query=query,
                        recommended_product=best_title,
                        reason=best_reason,
                        llm_response=llm_text
                    )
                    db.add(db_rec)
                    db.commit()
                    logger.info("Successfully persisted LLM recommendation report to SQLite.")
                except Exception as e:
                    logger.error(f"Failed to write recommendation to database: {e}")
                    db.rollback()
                    
            return parsed_recommendation
        else:
            logger.warning(
                f"LM Studio API returned error code {response.status_code}. "
                f"Falling back to heuristic ranking."
            )
    except Exception as e:
        logger.warning(
            f"Could not connect to LM Studio ({e}). "
            f"Ensure LM Studio is running. Activating fallback heuristic recommender."
        )
        
    # Fallback to local heuristic recommendation generator
    fallback_res = generate_heuristic_recommendation(query, products)
    
    if db:
        try:
            db_rec = DBRecommendation(
                query=query,
                recommended_product=fallback_res["best_choice"]["title"],
                reason=fallback_res["best_choice"]["reason"],
                llm_response=json.dumps(fallback_res)
            )
            db.add(db_rec)
            db.commit()
        except Exception as db_err:
            logger.error(f"Failed to log fallback recommendation to database: {db_err}")
            db.rollback()
            
    return fallback_res
